-- MySQL Script generated by MySQL Workbench
-- Wed Jan  8 09:42:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema asbl_projet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asbl_projet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asbl_projet` DEFAULT CHARACTER SET utf8 ;
USE `asbl_projet` ;

-- -----------------------------------------------------
-- Table `asbl_projet`.`Projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asbl_projet`.`Projects` (
  `project_id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `budget_estimated` DECIMAL NULL,
  `planned_date` DATETIME NULL,
  `account_number` VARCHAR(45) NOT NULL,
  `communication` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  `is_completed` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `category_id` INT NULL,
  `Projectscol` VARCHAR(45) NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asbl_projet`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asbl_projet`.`Categories` (
  `category_id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `Projects_project_id` INT NOT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `fk_Categories_Projects_idx` (`Projects_project_id` ASC) VISIBLE,
  CONSTRAINT `fk_Categories_Projects`
    FOREIGN KEY (`Projects_project_id`)
    REFERENCES `asbl_projet`.`Projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
