# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 16 Oct 2024 07:20:38 +0000
*               @ALL          0
*               @user         8
