# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 16 Oct 2024 07:20:38 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$tYGbTvGg3isHZpA3qVVs2.HtSe5tDxSfyCHhQGpg5i9VyWDXTsFkS:Abdoulaye Bayo:Abdulaibayobackend@gmail.com:admin,user
