# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 16 Oct 2024 11:25:45 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$LD8ZiJdLhvUomw3APSSYsOzmgxcoWBtgYnQxAHD6z1xCZPwXdcrrK:Abdoulaye Bayo:Abdulaibayo@outlook.fr:admin,user
