<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 30 Sep 2019 16:07:36 +0000
 */

$conf['title'] = 'Jeux de société';
$conf['lang'] = 'fr';
$conf['license'] = 'cc-by-sa';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
