<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Mon, 30 Sep 2019 16:02:40 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
